### ISSUE TITLE
Inline SVG XML gets compressed into oblivion

### ISSUE THREAD

**Issue by mcombuechen** [yui/yuicompressor#141]
I came across a situation where I wanted to save very small and simple SVG images inline in the CSS, e.g. 

``` css
div {
  background-image: url('data:image/svg+xml;utf8,<svg version="1.0" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="200px" height="200px" viewBox="0 0 200 200" xml:space="preserve"><polygon points="200,120 0,120 0,80 200,80 "/></svg>');
}
```

YUICompressor will strip all the whitespace from the XML and thus break it:

``` css
div{background-image:url('data:image/svg+xml;utf8,<svgversion="1.0"xmlns="http://www.w3.org/2000/svg"x="0px"y="0px"width="200px"height="200px"viewBox="00200200"xml:space="preserve"><polygonpoints="200,1200,1200,80200,80"/></svg>')}
```

I’d argue that content within `url()` shouldn’t be minified.
