### ISSUE TITLE
[2.4.8] Invalid reduction for keyframes

### ISSUE THREAD

**Issue by joni2back** [yui/yuicompressor#151]
Source: 
```css
@keyframes fadeIn {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
```
Output:
```css
@keyframes fadeIn{0{opacity:0}100%{opacity:1}}
```

Zero percent declaration loses the % char. Original="0%" - Compressed="0"
Usage: java -jar bin/yuicompressor-2.4.8.jar main.css
