### ISSUE TITLE
Arbitrary characters stripped from within url(...) resulting in incorrect url

### ISSUE THREAD

**Issue by 3dpie** [yui/yuicompressor#221]
Maybe something minor.. On an CSS error I came across, I ran some test cases with 2.4.8 and noticed an error with one particular font-face I obtained from Google fonts. The CSS is as follows:

```css
@font-face {
  font-family: 'Quicksand';
  font-style: normal;
  font-weight: 400;
  src: local('Quicksand Regular'), local('Quicksand-Regular'), url(https://fonts.gstatic.com/s/quicksand/v5/sKd0EMYPAh5PYCRKSryvW5Bw1xU1rKptJj_0jans920.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215, U+E0FF, U+EFFD, U+F000;
}
```
Source: https://fonts.googleapis.com/css?family=Quicksand

Note the url(...) on the 5th line:

`url(https://fonts.gstatic.com/s/quicksand/v5/sKd0EMYPAh5PYCRKSryvW5Bw1xU1rKptJj_0jans920.woff2)`

Note the beginning of the string after `https://.../quicksand/v5/`: `sKd0EMYPAh`. When I run `java -jar yuicompressor-2.4.8.jar quicksand.css`, the characters `EM` were stripped resulting in `sKd0YPAh` and therefore resulting in an invalid url: 

`url(https://fonts.gstatic.com/s/quicksand/v5/sKd0YPAh5PYCRKSryvW5Bw1xU1rKptJj_0jans920.woff2)`

As workaround, if I manually add a pair of single quotation marks around the http string, as in 
`url('https://fonts.gstatic.com/s/quicksand/v5/sKd0EMYPAh5PYCRKSryvW5Bw1xU1rKptJj_0jans920.woff2')`, no characters are stripped and the url string is intact. 

I tested with the latest codes from github, this problem still exists.

I tested against previous jar versions 2.4.7, 2.4.6 and 2.4.2, the problem did not occur. So it seems like this arbitrary stripping was introduced in 2.4.8.

I do not have the resource yet to test to see if this is a common occurrence or not.
Hope this is just something really minor.
