### ISSUE TITLE
broken output with data:image/svg+xml (bootstrap v4)

### ISSUE THREAD

**Issue by jsmad** [yui/yuicompressor#274]
yuicompressor fails to properly compress the bootstrap.css file from bootstrap v4, producing broken output for all image/svg+xml data.

original css:
```css
.navbar-inverse .navbar-toggler-icon{background-image:url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(255, 255, 255, 0.5)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 8h24M4 16h24M4 24h24'/%3E%3C/svg%3E")}
```

yuicompressor output:
```css
.navbar-inverse .navbar-toggler-icon{background-image:url("data:image/svg+xml;charset=utf8,%3CsvgviewBox='003232'xmlns='http://www.w3.org/2000/svg'%3E%3Cpathstroke='rgba(255,255,255,0.5)'stroke-width='2'stroke-linecap='round'stroke-miterlimit='10'd='M48h24M416h24M424h24'/%3E%3C/svg%3E")}
```

notice the missing spaces between the xml attributes, "svg viewBox" becomes "svgviewBox", etc.

I am not sure if this project is dead or not, the last release was several years ago...
