### ISSUE TITLE
Incorect default value for background-position

### ISSUE THREAD

**Issue by jmwebservices** [yui/yuicompressor#298]
[According to the spec](https://developer.mozilla.org/en-US/docs/Web/CSS/background-position), the default value for the 1-value syntax of background-position is 50% when the specified value is a length or percentage. However, the compressor forces a value of zero.

**Test case**
```css
test{
background-position: 0px;
}
```
**Expected result**
```css
test{background-position:0}
```
**Actual result**
```css
test{background-position:0 0}
```
