### ISSUE TITLE
confusing closing comments with opening comments

### ISSUE THREAD

**Issue by garretwilson** [yui/yuicompressor#313]
If the source file contains this:

```css
/*!
 * …
 */*,*::before,*::after{box-sizing:border-box} …
```

YUI Compressor gets confused and thinks the `/*` is the start of a _new_ comment, rather than the end of an existing comment, completely breaking the contents of the file, either by dropping the contents or including them as a comment (depending on the specific context).
