### ISSUE TITLE
CSS: Invalid whitespace removal / @supports () "or" ()

### ISSUE THREAD

**Issue by claudio147** [yui/yuicompressor#340]
If I combine certain properties in the **@support** query the whitespace after the "**or**" gets removed and this occurs invalid CSS (at least in Chrome)

Original:
```css
.foo {
    @supports (backdrop-filter: blur(10px)) or (-webkit-backdrop-filter: blur(10px)) {
        background: rgba(69, 69, 69, 0.5);
        backdrop-filter: blur(10px);
        -webkit-backdrop-filter: blur(10px);
      }
}
```

Compressed to:
```css
.foo {
    @supports (backdrop-filter: blur(10px)) or(-webkit-backdrop-filter: blur(10px)) {
        background: rgba(69, 69, 69, 0.5);
        backdrop-filter: blur(10px);
        -webkit-backdrop-filter: blur(10px);
      }
}
```
