### ISSUE TITLE
Opera device pixel ratio

### ISSUE THREAD

**Issue by ademey** [yui/yuicompressor#43]
The fraction used in a Opera device pixel ratio query will cause an issue. The following example:

``` css
  @media print,
         (-o-min-device-pixel-ratio: 5/4),
         (-webkit-min-device-pixel-ratio: 1.25),
         (min-resolution: 120dpi) {
      /* Style adjustments for high resolution devices */
  }

  @media print {
      * {
          background: transparent !important;
          color: #000 !important; /* Black prints faster: h5bp.com/s */
          box-shadow: none !important;
          text-shadow: none !important;
      }
  }
```

becomes:

``` css
@media print,(-o-min-device-pixel-ratio:5/@media print{*{background:transparent!important;color:#000!important;box-shadow:none!important;text-shadow:none!important}}
```

Using a decimal instead of a fraction fixes but Opera requires a fraction. I tested with version 2.4.7 and 2.4.8pre as part of ant-build-script.
