### ISSUE TITLE
Whitespace problem on filter:progid:DXImageTransform.Microsoft.Matrix

### ISSUE THREAD

**Issue by tinyhill** [yui/yuicompressor#64]
Considering following code:

``` css
.diamond {
  filter:progid:DXImageTransform.Microsoft.Matrix(M11=0.7071067811865475, M12=-0.7071067811865477, M21=0.7071067811865477, M22=0.7071067811865475, SizingMethod='auto expand');
}
```

The compressed result:

``` css
.diamond{filter:progid:DXImageTransform.Microsoft.Matrix(M11=0.7071067811865475,M12=-0.7071067811865477,M21=0.7071067811865477,M22=0.7071067811865475,SizingMethod='auto expand');}
```

This will not work in ie6, ie7 or other ie related browsers. Here's an article about this problem: https://clientsize.wordpress.com/2011/06/15/dximagetransform-microsoft-matrix-and-the-great-minify-mystery/
