### ISSUE TITLE
`0%` steps in @keyframe animations incorrectly changed to `0`

### ISSUE THREAD

**Issue by matthewrobb** [yui/yuicompressor#80]
Taking the following CSS:

``` css
@keyframe anim {
    0% { opacity: 0; }
  100% { opacity: 1; }
}
```

The output will be incorrectly rewritten to:

``` css
@keyframe anim {
    0 { opacity: 0; }
 100% { opacity: 1; }
}
```

This is not functionally equivalent.
