### ISSUE TITLE
HSL "%" being compressed away

### ISSUE THREAD

**Issue by whoughton** [yui/yuicompressor#81]
Best I can tell is that YUI compressor 2.4.8 is breaking hsl color values by removing the % in the S and L entries. Testing with:

``` css
.SB-messages .SB-message a {
    color: rgb(185, 99, 117);
    border-bottom: 1px dotted rgb(185, 99, 117;
    text-shadow: 0 1px 0 hsla(0, 0%, 0%, 1);
}
```

Produces:

``` css
.SB-messages .SB-message a{color:#b96375;border-bottom:1px dotted rgb(185,99,117;text-shadow:0 1px 0 hsla(0,0,0,1)}
```

Which does not work in chrome for me.
